export const slides = [
  {
    src: "/images/1.jpg",
    title: "Slide Title One",
    width: 1000,
    height: 1000,
    description: "Slide Description One\n\nthis is new line",
  },
  {
    src: "/images/2.jpg",
    title: "Slide Title Two",
    width: 1000,
    height: 1000,
    description: "Slide Description Two",
  },
  {
    src: "/images/3.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/4.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/5.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/6.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/7.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/8.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/9.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/10.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/11.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/12.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/13.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/14.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/15.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/16.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/17.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/18.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/19.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/20.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/21.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/22.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/23.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/24.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/25.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/26.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/27.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/28.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/29.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
  {
    src: "/images/30.jpg",
    title: "Slide Title Three",
    width: 1000,
    height: 1000,
    description: "Slide Description Three",
  },
];
